CREATE TABLE ADDRESS (
    ADDRESS_ID NUMBER(20) CONSTRAINT "ADDRESS_PK" PRIMARY KEY,
    STREET_NAME VARCHAR2(30),
    STREET_NUMBER NUMBER(4),
	APPARTMENT VARCHAR2(5)
	);
CREATE TABLE  CUSTOMERS(
	CUSTOMER_ID NUMBER(20) CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY, 
	ADDRESS_ID NUMBER(20) REFERENCES ADDRESS, 
	NAME VARCHAR2(20), 
	LAST_NAME VARCHAR2(30),
	EMAIL VARCHAR2(30) UNIQUE,
	PASSWORD VARCHAR2(15)
	);
CREATE TABLE  PAYMENT_TYPE (
	METHODS_ID NUMBER(20) CONSTRAINT "PAYMENT_TYPE_PK" PRIMARY KEY, 
	NAME VARCHAR2(30)
	);
CREATE TABLE  PAYMENT_METHOD (
	PAYMENT_ID NUMBER(20) CONSTRAINT "PAYMENT_METHOD_PK" PRIMARY KEY, 
	METHODS_ID NUMBER(20) REFERENCES PAYMENT_TYPE, 
	CUSTOMER_ID NUMBER(20) REFERENCES CUSTOMERS, 
	NAME VARCHAR2(35)
	);
CREATE TABLE CART (
	CART_ID NUMBER (20) CONSTRAINT PK_CART_ID PRIMARY KEY,
	CUSTOMER_ID NUMBER(20) REFERENCES CUSTOMERS,
	PRICE NUMBER(5,2),
	ORDER_DATE DATE
	);
CREATE TABLE CATEGORIES (
	CATEGORY_ID NUMBER (20) CONSTRAINT PK_CATEGORY_ID PRIMARY KEY,
	NAME VARCHAR2 (20));
CREATE TABLE PRODUCTS (
	PRODUCT_ID NUMBER (20) CONSTRAINT PK_PRODUCT_ID PRIMARY KEY,
	CATEGORY_ID NUMBER (20) REFERENCES CATEGORIES,
	NAME VARCHAR2 (30),
	DESCRIPTION VARCHAR2 (500),
	PRICE NUMBER (5,2),
	STOCK NUMBER (3),
	IMAGE VARCHAR2 (90));
	
CREATE TABLE CART_LINE (
	CART_LINE_ID NUMBER (20) CONSTRAINT PK_CART_LINE_ID PRIMARY KEY,
	PRODUCT_ID NUMBER (20) REFERENCES PRODUCTS,
	CART_ID NUMBER(20) REFERENCES CART,
	CANTIDAD NUMBER (2),
	PRICE NUMBER(5,2)
	);
