DROP TABLE CART_LINE;
DROP TABLE PRODUCTS;
DROP TABLE CATEGORIES;
DROP TABLE CART;
DROP TABLE ADDRESS;
DROP TABLE CUSTOMERS;

DESCRIBE CART;
DESCRIBE PRODUCTS;
DESCRIBE CATEGORIES;
DESCRIBE ORDERS;
DESCRIBE CUSTOMERS;
DESCRIBE ADDRESS;