DROP TABLE CART_LINE;
DROP TABLE PRODUCTS;
DROP TABLE CATEGORIES;
DROP TABLE CART;
DROP TABLE PAYMENT_METHOD;
DROP TABLE PAYMENT_TYPE;
DROP TABLE CUSTOMERS;
DROP TABLE ADDRESS;

DESCRIBE CART;
DESCRIBE PRODUCTS;
DESCRIBE CATEGORIES;
DESCRIBE PAYMENT_METHOD;
DESCRIBE PAYMENT_TYPE;
DESCRIBE ORDERS;
DESCRIBE CUSTOMERS;
DESCRIBE ADDRESS;