INSERT INTO ADDRESS (ADDRESS_ID, CUSTOMER_ID, STREET_NAME, STREET_NUMBER, APPARTMENT)
VALUES ('254029', '1', 'CALLE ALFONSO', '12', '3ºB');


INSERT INTO ADDRESS (ADDRESS_ID, CUSTOMER_ID, STREET_NAME, STREET_NUMBER, APPARTMENT)
VALUES ('254456', '2', 'SAN VICENTE DE PAUL', '56', '1ºC');


INSERT INTO ADDRESS (ADDRESS_ID, CUSTOMER_ID, STREET_NAME, STREET_NUMBER, APPARTMENT)
VALUES ('254387', '3', 'CALLE MARIO BROS', '17', '6ºD');


INSERT INTO ADDRESS (ADDRESS_ID, CUSTOMER_ID, STREET_NAME, STREET_NUMBER, APPARTMENT)
VALUES ('254012', '4', 'CALLE CANTANDO BAJO LA LLUVIA', '31', '9ºA');