INSERT INTO CATEGORIES (CATEGORY_ID, NAME)
VALUES ('1', 'GRANO');


INSERT INTO CATEGORIES (CATEGORY_ID, NAME)
VALUES ('2', 'TAZAS');


INSERT INTO CATEGORIES (CATEGORY_ID, NAME)
VALUES ('3', 'PACKS');