INSERT INTO CUSTOMERS (CUSTOMER_ID, ADDRESS_ID, NAME, LAST_NAME, EMAIL, PASSWORD)
VALUES ('1', '254029', 'ALBERTO', 'ZAPATER', 'azapater@gmail.com', 'ejea');


INSERT INTO CUSTOMERS (CUSTOMER_ID, ADDRESS_ID, NAME, LAST_NAME, EMAIL, PASSWORD)
VALUES ('2', '254456', 'CRISTIAN', 'ALVAREZ', 'calvarez@gmail.com','elsanto1234');


INSERT INTO CUSTOMERS (CUSTOMER_ID, ADDRESS_ID, NAME, LAST_NAME, EMAIL, PASSWORD)
VALUES ('3', '254387', 'BENITO ANTONIO', 'MARTINEZ','bamartinezpr@gmail.com', '4morfod4');


INSERT INTO CUSTOMERS (CUSTOMER_ID, ADDRESS_ID, NAME, LAST_NAME, EMAIL, PASSWORD)
VALUES ('4', '254012', 'ROMEO', 'SANTOS', 'rsantos@gmail.com','aventura');