/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.20
 * Generated at: 2022-05-12 19:10:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import com.sanvalero.coffea.domain.*;
import com.sanvalero.coffea.dao.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("com.sanvalero.coffea.dao");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.sanvalero.coffea.domain");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Coffea</title>\r\n");
      out.write("        <link href=\"../css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("        <script src=\"js/script2.js\"></script>\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Anton&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Rajdhani:wght@500;600&display=swap\"\r\n");
      out.write("              rel=\"stylesheet\">\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"padre\">\r\n");
      out.write("            <div class=\"arr\">\r\n");
      out.write("                <div class=\"parteizqarr\">\r\n");
      out.write("                    <div class=\"izq\">\r\n");
      out.write("                        <img src=\"../imagenes/logo.png\" class=\"logoarr\" alt=\"logo\">\r\n");
      out.write("                        <img src=\"../imagenes/cafe1.png\" class=\"imgizq\" alt=\"cafe\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"der\">\r\n");
      out.write("                        <div class=\"derarr\">\r\n");
      out.write("                            <div class=\"accesos\">\r\n");
      out.write("                                HOME\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"accesos\">\r\n");
      out.write("                                MENU\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"accesos\">\r\n");
      out.write("                                ABOUT US\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"derab\">\r\n");
      out.write("                            <div class=\"bestseller\">\r\n");
      out.write("                                BEST SELLER\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"productoprincipal\">\r\n");
      out.write("                                ");

                                    ProductDAO productDAO = new ProductDAO();
                                    productDAO.getProducts();
                                    Product bestSeller = productDAO.getBestSeller();
                                
      out.write("\r\n");
      out.write("                                ");
      out.print( bestSeller.getName());
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <img src=\"../imagenes/coffeeBag.png\" class=\"cafedelmedio\"\r\n");
      out.write("                                     alt=\"cafemedio\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"infoproducto\">\r\n");
      out.write("                                ");
      out.print( bestSeller.getDescription());
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"precioshop\">\r\n");
      out.write("                                $ ");
      out.print( bestSeller.getPrice());
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"shopnow\">\r\n");
      out.write("                                    SHOP NOW\r\n");
      out.write("                                    <img src=\"../imagenes/flecha-apuntando-hacia-la-izquierda-dentro-de-un-circulo (1).png\"\r\n");
      out.write("                                         class=\"flecha\" alt=\"flecha\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"partederarr\">\r\n");
      out.write("                    <div class=\"box\">\r\n");
      out.write("                        <div class=\"container-1\">\r\n");
      out.write("                            <img src=\"../imagenes/lupa.png\" class=\"lupa\" alt=\"lupa\">\r\n");
      out.write("                            <input type=\"search\" id=\"search\" placeholder=\"Search...\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <img src=\"../imagenes/custom_header.jpg\" class=\"imgprincipal\" alt=\"cafetal\">\r\n");
      out.write("                    <div class=\"infoimgprincipal\">\r\n");
      out.write("                        <h3>ETHICAL SOURCING</h3>\r\n");
      out.write("                        Our amazing coffee would not be possible without farmers all around the world.\r\n");
      out.write("                        That's why we work closely with them in order to ensure sustainable and ethically\r\n");
      out.write("                        sourced coffee.\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"abajo\">\r\n");
      out.write("                <div class=\"colores\">\r\n");
      out.write("                    <img src=\"../imagenes/separador.png\" class=\"separador\" alt=\"separador\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contactanos\">\r\n");
      out.write("                    <div class=\"contactanos-coffea\">\r\n");
      out.write("                        <h3>COFFEA</h3>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            Our company was made to offer our customers the best coffe in the world.\r\n");
      out.write("                            Our world renowned coffe has a 100% satisfaction rate among our customers.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <ul class=\"socials\">\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"../imagenes/twitter.png\" class=\"i\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"../imagenes/facebook.png\" class=\"i\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"../imagenes/instagram.png\" class=\"i\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"../imagenes/youtube.png\" class=\"i\"></a></li>\r\n");
      out.write("                            <li><a href=\"#\"><img src=\"../imagenes/pinterest.png\" class=\"i\"></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"colores\">\r\n");
      out.write("                    <img src=\"../imagenes/separador.png\" class=\"separador2\" alt=\"separador2\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
